module Luoma
  class AssignTag < Markup

    @name: Name

    @expression: Expression

    #  (t_token, Parser) -> Markup
    def self.parse: (t_token token, Parser parser) -> Markup

    #  (t_token, Name, Expression) -> void
    def initialize: (t_token token, Name name, Expression expression) -> void
  end
end