module Luoma
  class AssignTag < Markup

    @bindings: Array[Item]

    #  (t_token, String, Parser) -> Markup
    def self.parse: (t_token token, String tag_name, Parser parser) -> Markup

    #  (t_token, Array[Item]) -> void
    def initialize: (t_token token, String tag_name, Array[Item]) -> void
  end
end