module Luoma
  class EchoTag < Markup
    @expression: untyped

    #  (t_token, String, Parser) -> Markup
    def self.parse: (t_token token, String tag_name, Parser parser) -> Markup

    def initialize: (t_token token, String tag_name, Expression expression) -> void

  end
end