module Luoma
  class ForTag < Markup
    @params: Array[Name]

    @expression: Expression

    @block: t_block

    @default: t_block?

    END_FOR_BLOCK: Set[String]

    #  (t_token, String, Parser) -> Markup
    def self.parse: (t_token token, String tag_name, Parser parser) -> Markup

    #: (t_token, String, Array[Name], Expression, t_block, t_block?) -> void
    def initialize: (
      t_token token, 
      String tag_name, 
      Array[Name] params, 
      Expression expression, 
      t_block block, 
      t_block? default, 
      ) -> void
  end
end