module Luoma
  class ImportTag < Markup
    @template_name: Name

    @namespace: Name?

    #  (t_token, String, Parser) -> Markup
    def self.parse: (t_token token, String tag_name, Parser parser) -> Markup

    #  (t_token, String, Name?) -> void
    def initialize: (t_token token, String tag_name, Name template_name, Name? namespace) -> void
  end
end