module Luoma
  class IncludeTag < Markup
    @template_name: Expression

    @args: Array[KeywordArgument]

    #  (t_token, String, Parser) -> Markup
    def self.parse: (t_token token, String tag_name, Parser parser) -> Markup

    #  (t_token, String, Expression, Array[KeywordArgument]) -> void
    def initialize: (t_token token, String tag_name, Expression template_name, Array[KeywordArgument] args) -> void
  end
end