module Luoma
  class UnlessTag < Markup
    @alts: Array[UnlessBlock | IfBlock | ElseBlock]

    END_UNLESS_BLOCK: Set[String]

    UNLESS_BLOCKS: Set[String]

    #  (t_token, String, Parser) -> Markup
    def self.parse: (t_token token, String tag_name, Parser parser) -> Markup

    def initialize: (t_token token, String tag_name, Array[UnlessBlock | IfBlock | ElseBlock] alts) -> void
  end

  class UnlessBlock < Markup
    @expression: Expression

    @block: t_block

    attr_reader expression: Expression

    attr_reader block: t_block

    END_UNLESS_BLOCK: Set[String]

    #  (Parser) -> Markup
    def self.parse: (String tag_name, Parser parser) -> Markup

    def initialize: (t_token token, String tag_name, Expression expression, t_block block) -> void
    
    def filter_strings: () -> untyped
  end
end