module Luoma
  class ChoiceLoader < TemplateLoader
    @loaders: Array[TemplateLoader]

    def initialize: (*TemplateLoader loaders) -> void

    def load: (Environment env, String name, **untyped) -> Template
  end
end