module Luoma
  interface _Namespace
    def key?: (String) -> bool
    def fetch: (String, ?::Symbol default) -> untyped
    def []: (String) -> untyped
  end
                   
  interface _Tag
    def parse: (t_token, Parser) -> Markup
  end

  VERSION: String

  DEFAULT_ENVIRONMENT: Environment

  #: (String, ?globals: Hash[String, untyped]?) -> Template 
  def self.parse: (untyped source, ?globals: untyped?) -> untyped

  #: (String, ?Hash[String, untyped]?) -> String
  def self.render: (untyped source, ?untyped? data) -> untyped
end
