module Luoma
  type t_namespace = Hash[String, untyped]
                   
  interface _Tag
    def parse: (t_token, Parser) -> Markup
  end

  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
end
