module Luoma
  module Predicates
    #  (RenderContext, untyped) -> bool
    def self.null?: (RenderContext context, untyped obj) -> bool

    #  (RenderContext, untyped) -> bool
    def self.string?: (RenderContext context, untyped obj) -> bool

    #  (RenderContext, untyped) -> bool
    def self.number?: (RenderContext context, untyped obj) -> bool

    #  (RenderContext, untyped) -> bool
    def self.array?: (RenderContext context, untyped obj) -> bool

    #  (RenderContext, untyped) -> bool
    def self.object?: (RenderContext context, untyped obj) -> bool
                    
    #  (RenderContext, untyped) -> bool
    def self.numeric?: (RenderContext context, untyped obj) -> bool
  end
end