module Luoma
  # Combine multiple hashes for sequential lookup.
  class ChainHash
    @hashes: Array[Luoma::_Namespace]

    #  (*_Namespace) -> void
    def initialize: (*_Namespace hashes) -> void

    #  (String) -> untyped
    def []: (String key) -> untyped

    #  (String) -> bool
    def key?: (String key) -> untyped

    #  (String, untyped) -> untyped
    def fetch: (String key, ?untyped default) -> untyped

    def size: () -> Integer

    def push: (_Namespace hash) -> void

    alias << push

    def pop: () -> _Namespace?
  end
end