module Luoma
  class RenderContext
    @template: Template

    @env: Environment

    attr_reader env: Environment

    attr_reader template: Template

    #  (Template, ?globals: t_namespace?) -> void
    def initialize: (Template template, ?globals: t_namespace?) -> void
  end
end