module Luoma
  class RenderContext
    # The template being rendered.
    @template: Template

    # The Liquid environment this render context and associated template is
    # bound to.
    @env: Environment

    # Developer-defined template variables passed down from the environment
    # and template.
    @globals: _Namespace

    # The namespace for variables defined with `{% assign %}` and
    # `{% capture %}`.
    @locals: Hash[String, untyped]

    # A namespace for `{% increment %}` and `{% decrement %}`.
    @counters: Hash[String, untyped]

    # The current template scope including `locals`, `globals` and `counters`.
    # New block-scoped namespaces get pushed onto and popped off this chain
    # map.
    #
    # Scopes are searched from right to left. New scopes are push on the
    # right.
    @scopes: ChainHash

    # Names of tags that are disallowed in this context.
    @disabled_tags: Set[String]?

    # The number of times this render context has been extended or copied.
    @context_depth: Integer

    # A non-specific indicator of template local scope usage.
    @assign_score: Integer

    # A non-specific indicator of template local scope usage for the current
    # template and all partial templates combined.
    @assign_score_cumulative: Integer

    # The number of nodes rendered for the current template.
    @render_score: Integer

    # The number of nodes rendered for the current template and all partial
    # templates.
    @render_score_cumulative: Integer

    # A stack of interrupt signals used by `{% break %}` and
    # `{% continue %}`, for example.
    @interrupts: Array[Symbol]

    # A stack of `ForLoop` drops used to populate `forloop.parent`
    @forloops: Array[ForLoop]

    # Registers supporting stateful tags. It's OK to use this map for storing
    # custom tag state.
    @registers: Hash[Symbol, untyped]

    attr_reader env: Environment

    attr_reader template: Template

    attr_reader disabled_tags: Set[String]?

    attr_reader context_depth: Integer

    attr_reader assign_score: Integer

    attr_reader assign_score_cumulative: Integer

    attr_accessor render_score: Integer

    attr_accessor render_score_cumulative: Integer

    attr_accessor interrupts: Array[Symbol]

    attr_reader registers: Hash[Symbol, untyped]

    #  (Template, ?globals: _Namespace?) -> void
    def initialize: (Template template, ?globals: _Namespace?, ?disabled_tags: Set[String]?, ?context_depth: Integer?, ?assign_score_carry: Integer?, ?render_score_carry: Integer?) -> void

    #  (String) -> untyped
    def resolve: (String name) -> untyped

    #  (untyped, Array[untyped]) -> untyped
    def resolve_path: (untyped obj, untyped segments) -> untyped

    #  (String, untyped) -> void
    def assign: (String name, untyped value) -> void

    #  (_Namespace, bool?, Set[String]?, Template?) -> RenderContext
    def copy: (_Namespace namespace, ?block_scope: bool?, ?disabled_tags: Set[String]?, ?template: Template?) -> RenderContext

    #  (_Namespace, ?template: Template?) { () -> untyped } -> void
    def extends: (_Namespace namespace, ?template: Template?) { () -> untyped } -> void

    #  (String) -> Integer
    def decrement: (String name) -> Integer

    #  (String) -> Integer
    def increment: (String name) -> Integer
                 
    private

    #  (untyped) -> Integer
    def assign_score_of: (untyped value) -> Integer
                       
    #: () -> void
    def raise_for_context_depth: () -> void
                               
    #  (Array[untyped], untyped) -> untyped
    def resolve_array_segment: (Array[untyped] obj, untyped segment) -> untyped

    #  (String, untyped) -> untyped
    def resolve_string_segment: (String obj, untyped segment) -> untyped

    #  (Hash[untyped, untyped], untyped) -> untyped
    def resolve_hash_segment: (Hash[untyped, untyped] obj, untyped segment) -> untyped

    #  (untyped, untyped) -> untyped
    def resolve_unknown_segment: (untyped obj, untyped segment) -> untyped
  end
end