module Luoma
  class Drop
    include Enumerable[untyped]

    #  (untyped, RenderContext) -> bool
    def key?: (untyped obj, Luoma::RenderContext context) -> bool

    #  (String, RenderContext) -> untyped
    def fetch: (untyped name, Luoma::RenderContext context, ?default: untyped?) -> untyped

    def each: () ?{ (?) -> untyped } -> untyped
            
    def to_a: () -> Array[untyped]
            
    #  (untyped, RenderContext) -> bool
    def eq?: (untyped obj, Luoma::RenderContext context) -> bool

    #  (untyped, RenderContext) -> bool
    def lt?: (untyped obj, Luoma::RenderContext context) -> bool

    #  (untyped, RenderContext) -> bool
    def gt?: (untyped obj, Luoma::RenderContext context) -> bool
           
    #  (untyped, RenderContext) -> bool
    def contains?: (untyped obj, Luoma::RenderContext context) -> bool

    # Return the length of this object.
    # Along with `#slice`,  `#length` is part of the iterator protocol.
    #  (RenderContext) -> Integer
    def length: (Luoma::RenderContext context) -> Integer

    #  (Integer, Integer, Integer) -> Enumerable[untyped]
    def slice: (Integer start, Integer stop, Integer step) -> untyped

    #  (:data | :numeric | :string | :boolean, RenderContext) -> untyped
    def to_primitive: (:data | :numeric | :string | :boolean hint, Luoma::RenderContext context) -> untyped

    #  () -> String
    def to_s: () -> String

    #  () -> String?
    def to_html_safe_s: () -> String?
  end
end