module Luoma
  type t_namespace = Hash[String, untyped]

  interface _Namespace
    def key?: (String) -> bool
    def fetch: (String, ?::Symbol default) -> untyped
    def []: (String) -> untyped
    def nil?: () -> bool
  end
  
  interface _Lexer
    def tokenize: (Environment, String) -> Array[t_token]
  end

  interface _Parser
    def parse: (Environment, String, String, Array[t_token]) -> t_block
  end

  class Environment
    @auto_escape: bool?

    @auto_trim: '-' | '~' | nil

    @globals: t_namespace?

    @lexer: _Lexer

    @loader: TemplateLoader

    @parser: _Parser

    @strict_filters: bool

    @suppress_blank_control_flow_blocks: bool

    @undefined: singleton(UndefinedDrop)

    @tags: Hash[String, _Tag]

    @filters: Hash[String, untyped]

    @max_assign_score_cumulative: Integer?

    @max_assign_score: Integer?

    @max_context_depth: Integer

    @max_render_score_cumulative: Integer?

    @max_render_score: Integer?
    
    @max_render_size: Integer?

    @persistent_registers: Set[Symbol]

    attr_accessor auto_escape: bool?

    attr_accessor auto_trim: '-' | '~' | nil

    attr_accessor globals: t_namespace?

    attr_accessor lexer: _Lexer

    attr_accessor loader: TemplateLoader

    attr_accessor parser: _Parser

    attr_reader filters: Hash[String, untyped]

    attr_accessor strict_filters: bool

    attr_reader tags: Hash[String, _Tag]

    attr_accessor undefined: singleton(UndefinedDrop)

    attr_accessor max_assign_score_cumulative: Integer?

    attr_accessor max_assign_score: Integer?

    attr_accessor max_context_depth: Integer

    attr_accessor max_render_score_cumulative: Integer?

    attr_accessor max_render_score: Integer?

    attr_accessor max_render_size: Integer?

    attr_reader persistent_registers: Set[Symbol]

    def initialize: (
      ?auto_escape: bool?,
      ?auto_trim: ('-' | '~' | nil), 
      ?globals: t_namespace?, 
      ?lexer: _Lexer, 
      ?loader: TemplateLoader?, 
      ?parser: _Parser, 
      ?strict_filters: bool, 
      ?suppress_blank_control_flow_blocks: bool, 
      ?undefined: singleton(UndefinedDrop),
      ?max_assign_score_cumulative: Integer?,
      ?max_assign_score: Integer?,
      ?max_context_depth: Integer,
      ?max_render_score_cumulative: Integer?,
      ?max_render_score: Integer?,
      ?max_render_size: Integer?
    ) -> void

    #  (String,
    #   ?globals: t_namespace?,
    #   ?name: String?,
    #   ?overlay: t_namespace?,
    #   ?up_to_date: Proc::_Callable?) -> Template
    def parse: (String source, ?globals: t_namespace?, ?name: String?, ?overlay: t_namespace?, ?up_to_date: untyped?) -> Template

    #  (String, ?t_namespace?) -> String
    def render: (String source, ?t_namespace? data) -> String

    #  (String, ?globals: t_namespace?, ?context: RenderContext?, **untyped) -> Template
    def get_template: (String name, ?globals: t_namespace?, ?context: RenderContext?, **untyped kwargs) -> Template

    # Add or replace a filter. The same callable can be registered multiple times with
    # different names.
    #
    # If _callable_ accepts a keyword parameter called `context`, the active render
    # context will be passed to `#call`.
    #
    # @param name [String] The name of the filter, as used by template authors.
    # @param callable [responds to call] An object that responds to `#call(left, ...)`
    #   and `#parameters`. Like a Proc or Method.
    def register_filter: (String name, untyped callable) -> void

    # Remove a filter from the filter register.
    # @param name [String] The name of the filter.
    # @return [callable | nil] The callable implementing the removed filter, or nil
    #    if _name_ did not exist in the filter register.
    def delete_filter: (String name) -> void

    # Add or replace a tag.
    # @param name [String] The tag's name, as used by template authors.
    # @param tag [responds to parse: ([Symbol, String?, Integer], Parser) -> Tag]
    def register_tag: (String name, _Tag tag) -> void

    # Remove a tag from the tag register.
    # @param name [String] The name of the tag.
    # @return [_Tag | nil]
    def delete_tag: (String name) -> _Tag?

    #  () -> void
    def setup_tags_and_filters: () -> void

    #  (untyped, untyped, RenderContext, t_token) -> bool
    def contains?: (untyped left, untyped right, RenderContext context, t_token token) -> bool

    #  (untyped, untyped, RenderContext, t_token) -> bool
    def eq?: (untyped left, untyped right, RenderContext context, t_token token) -> bool

    #  (untyped, untyped, RenderContext, t_token) -> bool
    def lt?: (untyped left, untyped right, RenderContext context, t_token token) -> bool

    #  (untyped) -> bool
    def nothing?: (untyped obj) -> bool

    #  (untyped, RenderContext) -> bool
    def truthy?: (untyped obj, RenderContext context) -> bool

    #  (untyped, RenderContext, t_token) -> String
    def serialize: (untyped obj, RenderContext context, t_token token) -> String
                 
    #  (untyped, RenderContext, t_token) -> Array[untyped]
    def to_a: (untyped obj, RenderContext context, t_token token) -> Array[untyped]

    #  (untyped, RenderContext, t_token) -> Integer
    def to_i: (untyped obj, RenderContext context, t_token token) -> Integer

    #  (untyped, ?default: Numeric?) -> Numeric
    def to_numeric: (untyped obj, ?default: ::Numeric) -> Numeric

    # Cast `obj` to a number, favouring BigDecimal over Float.
    # Returns `default` if `obj` can't be cast to a numeric value.
    #  (untyped, ?default: Numeric?) -> Numeric
    def to_decimal: (untyped obj, ?default: ::Numeric) -> Numeric

    #  (untyped) -> Enumerable
    def to_enumerable: (untyped obj) -> Enumerable[untyped]

    #  (untyped, RenderContext, t_token) -> String
    def to_string: (untyped obj, RenderContext context, t_token token) -> String
                 
    # Cast _obj_ to a  date and time. Return `nil` if casting fails.
    # NOTE: This was copied from Shopify/liquid.
    def to_date: (untyped obj) -> untyped

    #  (String, String?, String?) -> String
    def trim: (String value, String? left, String? right) -> String

    #  (t_namespace?) -> t_namespace?
    def make_globals: (t_namespace? namespace) -> t_namespace?
  end
end