module Luoma
  class FilterContext
    @token: t_token

    @render_context: RenderContext

    @env: Environment

    attr_reader token: t_token

    attr_reader render_context: RenderContext

    attr_reader env: Environment

    #  (t_token, RenderContext)
    def initialize: (t_token token, RenderContext render_context) -> void
                  
    # (String) -> TemplateTypeError
    def type_error: (String message) -> TemplateTypeError
                  
    # (String) -> FilterArgumentError
    def argument_error: (String message) -> FilterArgumentError
                  
    #  (untyped) -> Array[untyped]
    def to_a: (untyped obj) -> Array[untyped]
            
    #  (untyped) -> Hash[untyped, untyped]
    def to_h: (untyped obj) -> Hash[untyped, untyped]

    # [X] (untyped, ?default: X) -> (Integer | X)
    def to_i: [X] (untyped obj, ?default: X) -> (Integer | X)

    #  (untyped) -> String
    def to_string: (untyped obj) -> String

    #  [X] (untyped, ?default: X) -> (Numeric | X)
    def to_numeric: [X] (untyped obj, ?default: X) -> (Numeric | X)

    #  (untyped) -> Enumerable[untyped]
    def to_enumerable: (untyped obj) -> Enumerable[untyped]
                     
    #  (untyped) -> untyped
    def to_date: (untyped obj) -> untyped
               
    #  (untyped) -> bool
    def nothing?: (untyped obj) -> bool
                
    #  (untyped) -> bool
    def truthy?: (untyped obj) -> untyped
               
    #  (untyped) -> bool
    def empty?: (untyped obj) -> bool
               
    #  (untyped, untyped, ?default: untyped?) -> untyped
    def fetch: (untyped obj, untyped key, ?default: untyped) -> untyped
  end
end
