module Luoma
  # A single-pass template tokenizer that matches Shopify/liquid v5.12.0 strict
  # mode syntax and semantics.
  #
  # We use lookahead and byte offset limits to achieve behavior equivalent to
  # Shopify's two-pass tokenizer/parser.
  class LegacyLexer < BaseLexer
    RE_MARKUP: ::Regexp

    RE_OUT_END: ::Regexp

    RE_TAG_END: ::Regexp

    RE_TRIVIA: ::Regexp

    RE_LINE_TRIVIA: ::Regexp

    RE_TAG_NAME: ::Regexp

    RE_PUNCTUATION: ::Regexp

    RE_IDENT: ::Regexp

    RE_FLOAT: ::Regexp

    RE_INT: ::Regexp

    RE_COMMENT_SEGMENT: ::Regexp

    RE_LINE_COMMENT_SEGMENT: ::Regexp

    RE_END_DOC: ::Regexp

    RE_END_RAW: ::Regexp

    RE_SINGLE_QUOTE: ::Regexp

    RE_DOUBLE_QUOTE: ::Regexp

    RE_NEWLINE: ::Regexp

    TOKEN_MAP: Hash[String, t_token_kind]

    #  () -> Symbol?
    def scan_markup: () -> Symbol?

    #  (Integer) -> void
    def accept_tag: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_expression: (Integer limit , ?Regexp trivia) -> void
                         
    #  (Integer) -> void
    def accept_inline_comment: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_block_comment: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_doc_comment: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_raw_tag: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_line_statements: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_line_block_comment: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_line_doc_comment: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_line_raw_tag: (Integer limit) -> void
                         
    #  (Integer) -> void
    def accept_string_literal: (Integer limit) -> void

    #  () -> bool
    def accept_whitespace_control: () -> bool
  end
end