module Luoma
  class UnifiedParser < Parser
    class Precedence
      LOWEST: Integer

      COALESCE: Integer

      LOGICAL_OR: Integer

      LOGICAL_AND: Integer

      LOGICAL_NOT: Integer

      COMPARISON: Integer

      MEMBERSHIP: Integer

      PIPE: Integer

      FILTER_ARG: Integer

      ADD: Integer

      MUL: Integer

      NEG: Integer

    end

    PRECEDENCES: Hash[t_token_kind, Integer]

    INFIX_OPERATORS: Hash[t_token_kind, untyped]

    TERMINATE_EXPRESSION: Set[t_token_kind]

    TERMINATE_FILTER: Set[t_token_kind]

    PATH_PUNCTUATION: Set[t_token_kind]

    STRING_LITERAL_KINDS: Set[t_token_kind]

    PATH_ROOT_KINDS: Set[t_token_kind]
    
    KEYWORD_ARGUMENT_DELIMITERS: Set[t_token_kind]

    RE_SLASH_U: ::Regexp

    RE_ESCAPE_INTERPOLATION: ::Regexp

    #  (?require_commas: bool?) -> Array[Expression | KeywordArgument]
    def parse_arguments: (?require_commas: bool?) -> Array[Expression | KeywordArgument]

    #  (?stop: Set[String]?) -> t_block
    def parse_block: (?stop: Set[String]?) -> t_block

    #  () -> Name
    def parse_ident: () -> Name

    #  (?require_commas: bool?) -> Array[KeywordArgument]
    def parse_keyword_arguments: (?require_commas: bool?) -> Array[KeywordArgument]

    # Parse an identifier, possibly surrounded by quotes.
    #  () -> Name
    def parse_name: () -> Name

    #  (?require_commas: bool?) -> Array[Expression]
    def parse_positional_arguments: (?require_commas: untyped?) -> Array[Expression]

    #  () -> StringLiteral
    def parse_string_literal: () -> StringLiteral

    #  (?precedence: Integer) -> Expression
    def parse_primary: (?precedence: Integer) -> Expression

    #  (Expression) -> Expression
    def parse_ternary: (Expression consequence) -> Expression

    #  () -> Expression
    def parse_array_or_path: () -> Expression

    #  (t_token, Expression|Spread) -> Expression
    def parse_partial_array: (t_token token, (Expression|Spread) first) -> Expression

    #  () -> ObjectLiteral
    def parse_object_literal: () -> ObjectLiteral

    #  () -> Item | Spread
    def parse_object_item: () -> (Item | Spread)

    #  (precedence: Integer) -> Expression
    def parse_lambda_range_or_group: (precedence: Integer) -> Expression

    #  (Expression, precedence: Integer) -> Lambda
    def parse_partial_lambda: (Expression expr, precedence: Integer) -> Expression

    #  () -> Expression
    def parse_prefix: () -> Expression

    #  () -> Markup
    def parse_output: () -> Markup

    #  () -> Markup
    def parse_comment: () -> Markup

    #  () -> Markup
    def parse_tag: () -> Markup

    #  () -> Variable
    def parse_path: () -> Variable

    #  () -> Array[t_path_segment]
    def parse_path_segments: () -> Array[t_path_segment]

    #  () -> t_path_segment
    def parse_bracketed_segment: () -> t_path_segment

    #  () -> Expression
    def parse_range_literal: () -> Expression

    #  () -> Expression
    def parse_true_literal: () -> Expression

    #  () -> Expression
    def parse_false_literal: () -> Expression

    #  () -> Expression
    def parse_null_literal: () -> Expression

    #  () -> Expression
    def parse_int_literal: () -> Expression

    #  () -> Expression
    def parse_float_literal: () -> Expression

    #  (t_token, Expression) -> FilteredExpression
    def parse_filter: (t_token token, Expression left) -> FilteredExpression
                    
    #  () -> Lambda
    def parse_lambda: () -> Lambda

    #  (Expression) -> Expression
    def parse_infix: (Expression left) -> Expression
                   
    def unescape: (t_token token) -> String

    def high_surrogate?: (Integer code_point) -> bool

    def low_surrogate?: (Integer code_point) -> bool
  end
end