module Luoma
  type t_block = Array[String | Luoma::Markup]
  class Template
    @env: Environment

    @source: String

    @nodes: t_block

    @globals: _Namespace?

    @name: String

    @overlay: _Namespace?

    @up_to_date: untyped

    attr_reader env: Environment

    attr_reader source: String

    attr_reader nodes: t_block

    attr_reader globals: _Namespace?

    attr_reader name: String

    attr_reader overlay: _Namespace?

    attr_reader up_to_date: untyped

    #  (Environment,
    #   String,
    #   t_block,
    #   ?globals: Hash[String, untyped]?,
    #   ?name: String?,
    #   ?overlay: Hash[String, untyped]?,
    #   ?up_to_date: Proc::_Callable?) -> void
    def initialize: (Environment env, String source, t_block nodes, ?globals: _Namespace?, ?name: String?, ?overlay: _Namespace?, ?up_to_date: untyped?) -> void

    #  (_Namespace?) -> String
    def render: (_Namespace? data) -> String

    #  (RenderContext, String) -> String
    def render_with_context: (RenderContext context, String buffer) -> String

    #  (_Namespace) -> Template
    def with_globals: (_Namespace namespace) -> Template

    #  (_Namespace?) -> _Namespace?
    def make_globals: (_Namespace? namespace) -> _Namespace?
  end
end