module Luoma
  class HTMLSafe < Drop
    @s: String

    #  (String | HTMLSafe) -> HTMLSafe
    def self.escape: (String | HTMLSafe value) -> HTMLSafe

    #  (String | HTMLSafe) -> HTMLSafe
    def self.from: (String | HTMLSafe value) -> HTMLSafe

    #  (String) -> void
    def initialize: (String s) -> void
  end
end