module Luoma
  class RangeDrop < Drop
    @start: Integer

    @stop: Integer

    @range: Enumerator[Integer]

    attr_reader start: Integer

    attr_reader stop: Integer

    #  (Integer, Integer) -> void
    def initialize: (Integer start, Integer stop) -> void
  end
end