module Luoma
  # Liquid filters and helper methods.
  module Filters
    # Return _left_, or _default_ if _obj_ is `nil`, `false` or empty.
    # If _allow_false_ is `true`, _left_ is returned if _left_ is `false`.
    def self.default: (FilterContext context, untyped left, ?::String default, ?allow_false: bool) -> untyped
  end
end