module Luoma
  module Filters
    def self.slice: (
      FilterContext context, 
      untyped left, 
      ?untyped start_, ?untyped stop_, ?untyped step_, 
      ?start: untyped, ?stop: untyped, ?step: untyped
    ) -> Array[untyped]
  end
end