module Luoma
  module Filters
    INFINITY_ARRAY: ::Array[untyped]

    def self.sort: (FilterContext context, untyped left, ?untyped? key) -> untyped

    def self.sort_numeric: (FilterContext context, untyped left, ?untyped? key) -> untyped

    def self.numeric_compare: (untyped left, untyped right, FilterContext context) -> untyped

    def self.ints: (untyped obj, FilterContext context) -> (::Array[untyped] | untyped)
  end
end