module Luoma
  module Filters
    INFINITY_ARRAY: ::Array[untyped]

    def self.sort: (FilterContext context, untyped left, ?untyped? key) -> untyped

    def self.sort_natural: (FilterContext context, untyped left, ?untyped? key) -> untyped

    def self.sort_numeric: (FilterContext context, untyped left, ?untyped? key) -> untyped

    def self.nil_safe_casecmp: (untyped left, untyped right) -> (untyped | 0 | 1 | -1)

    def self.numeric_compare: (untyped left, untyped right) -> untyped

    def self.ints: (untyped obj) -> (::Array[untyped] | untyped)
  end
end